<a href="https://colab.research.google.com/github/rafiqulcse/Natural-Language-Processing-Project/blob/main/Multi_Layer_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Google Colab Link: https://colab.research.google.com/drive/1Y4CuujhJS9cPWcM9tX1685yNkoLt7WSk?usp=sharing

# **Import Libraries**

In [1]:
import os
import shutil

import tensorflow as tf
import tensorflow_hub as hub
import matplotlib.pyplot as plt

tf.get_logger().setLevel('ERROR')

In [2]:
import pandas as pd

In [3]:
github_url = "https://raw.githubusercontent.com/rafiqulcse/Natural-Language-Processing-Project/main/Dataset/NLP-project-dataset.csv"

df = pd.read_csv(github_url)
df.head()

clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...         0
3  for your own benefit you may want read living ...         1
4  you should all sit down together and watch the...         0

# **Preprocess Dataset**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split

In [ ]:
tfidf = TfidfVectorizer(analyzer = 'word', max_features = 150)
X = tfidf.fit_transform(df['clean_comment'])
X

<2000x150 sparse matrix of type '<class 'numpy.float64'>'
	with 23406 stored elements in Compressed Sparse Row format>

In [ ]:
y = df['category']
X = X.toarray()
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.19244986, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.53784513,
        0.21820747],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
X = pd.DataFrame(X)
X

0        1    2    3         4         5         6    7         8    \
0     0.0  0.00000  0.0  0.0  0.169990  0.000000  0.109950  0.0  0.000000   
1     0.0  0.19245  0.0  0.0  0.060310  0.229569  0.312071  0.0  0.000000   
2     0.0  0.00000  0.0  0.0  0.178172  0.000000  0.230484  0.0  0.108718   
3     0.0  0.00000  0.0  0.0  0.000000  0.000000  0.091696  0.0  0.086505   
4     0.0  0.00000  0.0  0.0  0.313433  0.000000  0.202730  0.0  0.000000   
...   ...      ...  ...  ...       ...       ...       ...  ...       ...   
1995  0.0  0.00000  0.0  0.0  0.000000  0.000000  0.164056  0.0  0.000000   
1996  0.0  0.00000  0.0  0.0  0.000000  0.000000  0.000000  0.0  0.000000   
1997  0.0  0.00000  0.0  0.0  0.000000  0.000000  0.000000  0.0  0.000000   
1998  0.0  0.00000  0.0  0.0  0.000000  0.000000  0.000000  0.0  0.000000   
1999  0.0  0.00000  0.0  0.0  0.000000  0.000000  0.000000  0.0  0.000000   

           9    ...       140       141  142       143       144  145  \
0     0.000000  ...  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
1     0.102578  ...  0.000000  0.064737  0.0  0.121454  0.171557  0.0   
2     0.075761  ...  0.136732  0.000000  0.0  0.089702  0.000000  0.0   
3     0.060282  ...  0.000000  0.000000  0.0  0.000000  0.268847  0.0   
4     0.000000  ...  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
...        ...  ...       ...       ...  ...       ...       ...  ...   
1995  0.000000  ...  0.000000  0.272257  0.0  0.000000  0.000000  0.0   
1996  0.000000  ...  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
1997  0.000000  ...  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
1998  0.000000  ...  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
1999  0.105700  ...  0.000000  0.000000  0.0  0.125151  0.000000  0.0   

           146  147       148       149  
0     0.000000  0.0  0.000000  0.000000  
1     0.139404  0.0  0.000000  0.000000  
2     0.000000  0.0  0.537845  0.218207  
3     0.000000  0.0  0.305682  0.434060  
4     0.000000  0.0  0.270330  0.000000  
...        ...  ...       ...       ...  
1995  0.293140  0.0  0.000000  0.000000  
1996  0.000000  0.0  0.000000  0.000000  
1997  0.000000  0.0  0.000000  0.000000  
1998  0.000000  0.0  0.000000  0.000000  
1999  0.000000  0.0  0.000000  0.000000  

[2000 rows x 150 columns]

In [ ]:
feature = tfidf.vocabulary_
col_names = []

In [ ]:
for key, value in feature.items():
    print(key, ' : ', value)
    col_names.append(key)

have  :  50
never  :  77
them  :  117
they  :  121
still  :  108
from  :  38
time  :  127
like  :  63
some  :  104
come  :  21
for  :  37
the  :  115
and  :  6
all  :  4
things  :  123
has  :  48
very  :  129
much  :  74
lot  :  64
with  :  144
that  :  114
are  :  9
same  :  98
thing  :  122
want  :  131
going  :  42
about  :  1
way  :  133
this  :  125
would  :  146
don  :  30
will  :  143
but  :  19
could  :  24
also  :  5
one  :  81
such  :  109
there  :  119
what  :  136
well  :  134
many  :  68
believe  :  15
said  :  97
see  :  101
how  :  55
man  :  67
into  :  58
should  :  103
someone  :  105
because  :  11
out  :  85
who  :  141
just  :  60
can  :  20
something  :  106
than  :  113
right  :  96
say  :  99
first  :  36
get  :  40
its  :  59
too  :  128
people  :  88
then  :  118
doesn  :  29
you  :  148
any  :  8
your  :  149
while  :  140
these  :  120
may  :  69
being  :  14
new  :  78
their  :  116
not  :  79
where  :  138
make  :  66
down  :  31
was  :  132
when  :  137
m

In [ ]:
X.columns = col_names
col_names
X

have    never  them  they     still      from      time  like      some  \
0      0.0  0.00000   0.0   0.0  0.169990  0.000000  0.109950   0.0  0.000000   
1      0.0  0.19245   0.0   0.0  0.060310  0.229569  0.312071   0.0  0.000000   
2      0.0  0.00000   0.0   0.0  0.178172  0.000000  0.230484   0.0  0.108718   
3      0.0  0.00000   0.0   0.0  0.000000  0.000000  0.091696   0.0  0.086505   
4      0.0  0.00000   0.0   0.0  0.313433  0.000000  0.202730   0.0  0.000000   
...    ...      ...   ...   ...       ...       ...       ...   ...       ...   
1995   0.0  0.00000   0.0   0.0  0.000000  0.000000  0.164056   0.0  0.000000   
1996   0.0  0.00000   0.0   0.0  0.000000  0.000000  0.000000   0.0  0.000000   
1997   0.0  0.00000   0.0   0.0  0.000000  0.000000  0.000000   0.0  0.000000   
1998   0.0  0.00000   0.0   0.0  0.000000  0.000000  0.000000   0.0  0.000000   
1999   0.0  0.00000   0.0   0.0  0.000000  0.000000  0.000000   0.0  0.000000   

          come  ...   muslims  politics  few      vote   country  please  \
0     0.000000  ...  0.000000  0.000000  0.0  0.000000  0.000000     0.0   
1     0.102578  ...  0.000000  0.064737  0.0  0.121454  0.171557     0.0   
2     0.075761  ...  0.136732  0.000000  0.0  0.089702  0.000000     0.0   
3     0.060282  ...  0.000000  0.000000  0.0  0.000000  0.268847     0.0   
4     0.000000  ...  0.000000  0.000000  0.0  0.000000  0.000000     0.0   
...        ...  ...       ...       ...  ...       ...       ...     ...   
1995  0.000000  ...  0.000000  0.272257  0.0  0.000000  0.000000     0.0   
1996  0.000000  ...  0.000000  0.000000  0.0  0.000000  0.000000     0.0   
1997  0.000000  ...  0.000000  0.000000  0.0  0.000000  0.000000     0.0   
1998  0.000000  ...  0.000000  0.000000  0.0  0.000000  0.000000     0.0   
1999  0.105700  ...  0.000000  0.000000  0.0  0.125151  0.000000     0.0   

      corruption  delhi    search       aap  
0       0.000000    0.0  0.000000  0.000000  
1       0.139404    0.0  0.000000  0.000000  
2       0.000000    0.0  0.537845  0.218207  
3       0.000000    0.0  0.305682  0.434060  
4       0.000000    0.0  0.270330  0.000000  
...          ...    ...       ...       ...  
1995    0.293140    0.0  0.000000  0.000000  
1996    0.000000    0.0  0.000000  0.000000  
1997    0.000000    0.0  0.000000  0.000000  
1998    0.000000    0.0  0.000000  0.000000  
1999    0.000000    0.0  0.000000  0.000000  

[2000 rows x 150 columns]

# **Training-Testing Split**

In [ ]:
X.shape, y.shape
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train.shape

(1600, 150)

# **MLP Model Implementation**

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
mlp = MLPClassifier(hidden_layer_sizes=(3,2), max_iter=500, activation='relu')

In [ ]:
mlp.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(3, 2), max_iter=500)

# **Testing**

In [ ]:
pred = mlp.predict(X_test)
pred

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

# **Model Evaluation**

In [ ]:
confusion_matrix(y_test, pred)

array([[ 65,  66],
       [ 75, 194]])

In [ ]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.46      0.50      0.48       131
           1       0.75      0.72      0.73       269

    accuracy                           0.65       400
   macro avg       0.61      0.61      0.61       400
weighted avg       0.65      0.65      0.65       400

